### ISSUE TITLE
Speedup Unmarshalling 

### ISSUE THREAD

**Issue by nikolaydubina** [ferdypruis/iso4217#4]
Hi, thanks for awesome lib! I like how you structured currencies, methods, iota. very good.

I used it in my fpmoney package: https://github.com/nikolaydubina/fpmoney

I noticed that casting string or []byte to this enum is prohibitively expensive. It is more expensive that just string.

- current code is like 1500ns 
- string / int / float 400ns+
- switch case cast -> 300ns

I suggest you switching to switch case + adding benchmarks in this repo.

Please refer to repo for details.

Thanks! 

once again, nice work!

**Comment by ferdypruis** [comment]
Hi Nikolay, and thank you.

I shall add the same sort of lookups as I have in my iso3166-pkg to improve resolving string values to constants.

**Comment by ferdypruis** [comment]
This change has a side-effect of fixing a bug where a historic currency would be returned for a reused numeric code. 
For example 008 would result in ALK instead of ALL.

**Comment by ferdypruis** [comment]
Please give v1.2.1 a try

**Comment by nikolaydubina** [comment]
Works like a charm. Thanks!
