### ISSUE TITLE
Non English names generation

### ISSUE THREAD

**Issue by gedw99** [ferdypruis/iso4217#6]
Would be useful if non english names can also be generated.

My use case is that i need to support currencies and the user are not all English speakers, so it would be handy if the other currency names can be also generated.

https://github.com/ferdypruis/iso4217/blob/master/generator/data.go.tpl#L22 

We could use  Constants or a maps to hold all non english names,
The English name coudl be used as the key to map to the non english names.

**Comment by gedw99** [comment]
I had a look at the 2 data files, and i am not that familiar with the schema but i don't think it has the non english names.

**Comment by gedw99** [comment]
ah i see. Yeah i don't know where those non english representations would be.
If i recall, I dug into the the ISO 4217 data to see if they were there in the data, but i got lost in the way their data is structured actually, hence why i asked you , figuring that you knew that data structure.

I think your right in that the best way is to find a mapping of English currency names to non english currency names.

I did some digging and got lucky !!

List of all currencies with names and ISO 4217 codes in all languages and all data formats.
https://github.com/umpirsky/currency-list

I think this will work. What ya think ??

**Comment by ferdypruis** [comment]
That looks promising.
I'll look into whether it's worth porting to a Go package.

**Comment by JGConsulting** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
notatestuser, @qpakzk, @Jeongseup, @boohyunsik, @ccwxl, @infojunkie, @hotraygroup, @mpk2, @snehesht, @Xuanwo, @ArnonHongklay, @bagaking, @foyun2013, @neeker, @hrishikeshio, @marvin-liu-sx, @nasjp, @nikli2009, @dangorst1066, @devnulled
